cupofdata/cupofdata.com

- .gitignore
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- README.md
> Docs update

- CODE_OF_CONDUCT.md
- src/containers/AutomatedMarketing/index.js
- src/containers/BannerSection/index.js
- src/containers/Benefits/index.js
- src/containers/Contact/index.js
- src/containers/Features/index.js
- src/containers/Feedback/index.js
- src/containers/Footer/index.js
> Text updates

- src/html.js
Remove extra Segment script snippet from index.js.
> remove segmentjs from index.js

- src/components/Navbar.js
- src/config/constants.js
- src/containers/Contact/index.js
> remove github icon and link

- src/pages/404.js
replace padding to margin for 404 page
> Feature: replace padding to margin in 404 page - Issue #31

- src/pages/404.js
> Replace Unit

- src/components/Button.js
- src/pages/404.js
> Fix 404 page re-rendering

- gatsby-config.js
- src/containers/Footer/index.js
- src/containers/Navbar/index.js
- src/pages/about/about.md
> Update Company texts

- src/components/Global.js
- src/pages/about/about.md
> update image paths

- src/containers/Feedback/index.js
- src/containers/Navbar/index.js
- src/containers/News/index.js
> Added launch news item to main page

- src/containers/Navbar/index.js
- src/layouts/index.js
- src/pages/onboard.js
> Lead capture bot

- src/containers/AutomatedMarketing/index.js
> Add link to onboarding

- src/containers/Navbar/index.js
> Dropdown navbar responsive

- gatsby-config.js
- package.json
- src/containers/BannerSection/index.js
- src/layouts/index.js
- src/pages/blog.js
- src/pages/index.js
- src/pages/onboard.js
- src/templates/about.js
- src/templates/blog.js
> fix blog page reload issue

- src/layouts/index.js
- src/templates/about.js
> update company profile page

- src/pages/onboard.js
> Manage onboarding links as environment variables

- src/containers/Contact/index.js
- src/pages/blog.js
> Fix blog typo

- src/containers/Pricing/FAQ/index.js
- src/containers/Pricing/PriceSection/index.js
> Update pricing page texts

- package.json
- src/config/constants.js
- src/containers/Contact/index.js
- src/styles/global.js
> social media links providing right functionality

- src/containers/Home/Features/index.js
Closes #102 
I have removed this button by annotating for feature page in the future.
> Fix learn more button.

- src/pages/pricing.js
> Fix pricing page title

- package.json
- src/components/AvatarCard.js
- src/components/Button.js
- src/containers/Home/News/index.js
- src/pages/index.js
- static/admin/config.yml
> edit news from cms

- src/containers/Home/BannerSection/index.js
- src/containers/Home/Benefits/index.js
- src/containers/Home/Features/index.js
- src/containers/Navbar/index.js
- src/pages/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
- src/styles/global.js
> Fix responsive page

- src/containers/Contact/index.js
> Add pricing link in contact section

- src/layouts/index.js
> Fix hiding nav in onboard refresh

- gatsby-config.js
- package.json
- src/html.js
> Fix favicon

- src/components/Button.js
- src/containers/Home/BannerSection/index.js
- static/files/images/mobile-background.svg
> mobile responsive for banner section

- .prettierrc
- gatsby-config.js
- gatsby-node.js
- package-lock.json
- package.json
- src/components/AvatarCard.js
- src/components/Button.js
- src/components/Layout.js
- src/components/PriceCard.js
- src/components/Typography.js
- src/config/constants.js
- src/html.js
- src/layouts/index.js
- src/pages/404.js
- src/pages/blog.js
- src/pages/index.js
- src/pages/onboard.js
- src/pages/pricing.js
- src/styles/theme.js
- src/templates/about.js
- src/templates/blog.js
- src/templates/faq.js
- src/templates/legal.js
- src/templates/testimonials.js
> Implemented prettier

- content/faq/2018-02-17-do-you-augment-account-and-contact-lists-with-context.md
- content/faq/2018-02-17-do-you-integrate-with-crm-and-martech-solutions.md
- content/faq/2018-02-17-do-you-leverage-third-party-databases.md
- content/faq/2018-02-17-do-you-offer-free-trials-for-your-services.md
- content/faq/2018-02-17-how-is-your-service-different-from-all-other-b2b-lead-gen-services-out-there.md
- content/faq/2018-02-17-what-forms-of-payment-do-you-accept.md
> Updated FAQs

- src/containers/Home/BannerSection/index.js
> update banner text

- src/components/PriceCard.js
- src/containers/Home/News/index.js
- src/containers/Navbar/index.js
- src/pages/blog.js
> Converted fake links to proper link tags

- src/containers/Home/BannerSection/index.js
> Banner main text update

- src/containers/Pricing/PriceSection/index.js
> Fix annual typo

- content/blog/2018-02-06-announcing-insights-network-contribution-and-tiers.md
- content/blog/2018-02-07-a-i-and-account-based-marketing-abm.md
- content/blog/2018-02-08-ai-models-for-marketers-and-flight-simulators.md
- content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
- content/blog/2018-03-04-b2b-leads-challenges-and-opportunities.md
> add blog to relative path

- src/containers/Contact/index.js
> Update mission statement

- src/templates/blog.js
> Remove disqus from blog entries

- content/about/about.md
> Move images to files -> images

- package-lock.json
- package.json
> force 1.3.5 with resolution

- content/testimonials/anna-anisin.md
- content/testimonials/tj_bramblett.md
- static/admin/config.yml
> Fix testimonial paths

- README.md
- src/layouts/index.js
- src/pages/beta.js
> New beta form

- gatsby-config.js
- package-lock.json
- package.json
- src/pages/404.js
> Add page title to 404 for tracking

- content/blog/2018-02-08-cup-of-data-a-marketing-science-solution-for-account-based-marketing-launches-at-data-science-salon-miami.md
- content/features/improve-prospect-quality-scores-with-machine-learning.md
- content/features/obtain-insights-on-how-to-engage-contacts-with-context.md
- content/features/quickly-identify-relevant-accounts-and-contacts.md
- content/features/quickly-identify-relevant-accounts-and-contacts2.md
- content/testimonials/anna-anisin.md
- content/testimonials/tj_bramblett.md
- gatsby-node.js
- src/components/Button.js
- src/components/Contact.js
- src/components/Home/BannerSection.js
- src/components/Home/Benefits.js
- src/components/Home/Features.js
- src/components/Home/HowItWorks.js
- src/components/Home/News.js
- src/components/Home/Testimonials.js
- src/components/Navbar.js
- src/components/PriceCard.js
- src/components/Pricing/FAQ.js
- src/components/Pricing/PriceSection.js
- src/components/Typography.js
- src/pages/blog.js
- src/pages/index.js
- src/templates/blog.js
- src/templates/feature.js
- src/templates/legal.js
- src/templates/testimonial.js
- static/admin/config.yml
> features update, included some cleanup too

- content/home-banner/banner.md
- src/components/Home/BannerSection.js
- src/pages/index.js
- src/templates/banner.js
- static/admin/config.yml
> CMS updates for home banner

- src/components/Pricing/PriceSection.js
> Change free trial text

- gatsby-config.js
- src/templates/blog.js
> Remove disqus references

- src/components/Layout.js
- src/styles/global.js
> updated styles

- src/components/Contact.js
- src/components/Home/AutomatedMarketing.js
- src/components/Home/BannerSection.js
- src/components/Home/Benefits.js
- src/components/Home/Features.js
- src/components/Home/HowItWorks.js
- src/components/Home/News.js
- src/components/Navbar.js
- src/components/PriceCard.js
- src/components/Pricing/FAQ.js
- src/components/Pricing/PriceSection.js
- src/components/Typography.js
- src/layouts/index.js
- src/styles/global.js
- src/styles/theme.js
- src/templates/about.js
> Font styles

- static/admin/config.yml
> Update pricing with CMS

- content/automatedmarketing/let-us-help-you-get-started-on-us.md
- src/components/Home/AutomatedMarketing.js
- src/components/Layout.js
- src/pages/index.js
- src/templates/automatedmarketing.js
- static/admin/config.yml
> Update automated marketing section with CMS

- src/components/Contact.js
> Update about link

- static/admin/config.yml
> Enable editorial workflow

- LICENSE.md
- README.md
> License and readme update

- static/admin/config.yml
> Git backend

- .eslintrc
- gatsby-config.js
- package-lock.json
- package.json
- yarn.lock
> Initial ESLint config

- content/automatedmarketing/let-us-help-you-get-started-on-us.md
- content/feature-banner/feature-banner.md
- src/components/Features/BannerSection.js
- src/components/Home/AutomatedMarketing.js
- src/components/Home/BannerSection.js
- src/pages/features.js
- src/pages/index.js
- src/templates/featureBanner.js
- static/admin/config.yml
> Button with cms in features page

- static/admin/config.yml
> goofed and forgot automated mktg button string

- src/components/Pricing/PriceSection.js
> Fix pricing link for enterprise

- src/components/NotFound.js
- src/pages/404.js
- src/templates/pageNotFound.js
Removed lazy loading. Not that important here. [Using custom themes with styled components apparently is an issue](https://github.com/gatsbyjs/gatsby/pull/5583), so imported theme explicitly. Closes #331
> Fix 404 page
